modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="backpacked"
version="1.7.0"
displayName="Backpacked"
updateJSONURL="https://raw.githubusercontent.com/MrCrayfish/ModUpdates/master/backpacked/update.json"
displayURL="https://mrcrayfish.com/mods?id=backpacked"
logoFile="backpacked.png"
credits=""
authors="MrCrayfish"
description="Adds a simple backpack to store more items"

[[dependencies.backpacked]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.backpacked]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
[[dependencies.backpacked]]
    modId="curios"
    mandatory=false
    versionRange="[1.0.6,)"
    ordering="AFTER"
    side="BOTH"