modLoader="javafml"
loaderVersion="[32,)"
license="GNU General Public License 3"

[[mods]]
modId="backpacked"
version="1.5.1"
displayName="Backpacked"
updateJSONURL="https://raw.githubusercontent.com/MrCrayfish/ModUpdates/master/backpacked/update.json"
displayURL="https://mrcrayfish.com/mods?id=backpacked"
logoFile="backpacked.png"
credits=""
authors="MrCrayfish"
description="Adds a simple backpack to store more items"

[[dependencies.backpacked]]
    modId="forge"
    mandatory=true
    versionRange="[32.0.97,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.backpacked]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1,1.17)"
    ordering="NONE"
    side="BOTH"
[[dependencies.backpacked]]
    modId="curios"
    mandatory=false
    versionRange="[3.0,)"
    ordering="AFTER"
    side="BOTH"