modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="modid"
version="version"
displayName="name"
updateJSONURL="https://raw.githubusercontent.com/MrCrayfish/MiniMods/${mod.repo_name}/update.json"
displayURL="https://mrcrayfish.com/minimods"
logoFile=""
credits=""
authors="MrCrayfish"
description="description"

[[dependencies.modid]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.modid]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"